---
title: "dennis_r"
num_samples: 20
path: "smooth"
random: True
generate_dataset: False
split:
 - 70
 - 20
 - 10

lighting:
 light_type: "POINT"
 light_energy: 1000

obj:
 focal_length: 0.8
 scale:
  - 0.1
  - 0.1
  - 0.1

camera:
 initial:
  rotate: True
  angle: 210
 rotation: 
  degrees: -78.96
  interval: 1
  negative: True
 random_uniform:
  low:
   - -20
   - -20
   - 20
  high:
   - 20
   - 20
   - 22
 location:
  - -18.72
  - 18.66
  - 17.36

s